### ISSUE TITLE
Display flip

### ISSUE THREAD

**Issue by Szprej0** [SpacehuhnTech/HackHeld#7]
Hi, I'm using Hackheld firmware on my NodeMCU and I have a different display position (flipped upside down). Can I flip the display in the firmware? I was using a (.bin) file to program

**Comment by super-octol-tool** [comment]
Sorry don't know much about the NodeMCU and Hackheld firmware is pretty advanced for someone like U. You need to read some more. I'll get to you......Please note that the ESP8266 does only support 2.4GHz you need not creat fake networks if you have three or four devices which you can link together .

**Comment by Szprej0** [comment]
Never mind i just downloaded the Arduino version and modified it to my preferences.
