### ISSUE TITLE
Alternative firmwares?

### ISSUE THREAD

**Issue by virtadpt** [SpacehuhnTech/HackHeld#8]
This may be an elementary question, and for that I apologize in advance.  Would it be feasible to install Circuitpython or MicroPython on one of these units, or does the hardware have functionality that would preclude doing so?

**Comment by spacehuhn** [comment]
There is Micropython for the ESP8266, so yes should be possible.

**Comment by virtadpt** [comment]
Thank you very much for the answer, I really appreciate it (without having to risk bricking my device). Onward!
